title: ABI Unit Test Results
description: I want to write it down, and for it to be pretty.
baseurl: "/splice-experiment-results"
url: ""
repository: buildsi/splice-experiment-results
paginate: 28

banner: "/assets/img/banner.png" # site banner (load when someone share your page url)
favicon: "/assets/img/favicon.ico" # site's favicon (icon left side of your page)

# Collections
collections:
  results:
    output: true
    permalink: /:collection/:path

defaults:
  - scope:
      path: "_results"
      type: "results"
    values:
      layout: "result"

user: 
  avatar: "/assets/img/logo.png"
  github: "vsoch"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title

plugins:
  - jekyll-scholar
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
